### ISSUE TITLE
build error with Angular 8.0.0  (TypeError: Cannot read property 'Promise' of undefined)

### ISSUE THREAD

**Issue by anisabboud** [RaphaelJenni/FirebaseUI-Angular#93]
I updated my project to the latest `Angular 8.0.0`, `@angular/fire 5.2.0-rc.1`, `firebase 6.1.0`, `firebaseui 4.0.0`, `firebaseui-angular 3.4.2`.

`ng serve` works well. With `ng build` or `ng build --prod`, the build succeeds but I get a console error.

```
Uncaught TypeError: Cannot read property 'Promise' of undefined
    at da (npm.js:73)
    at npm.js:74
    at npm.js:425
    at Object../node_modules/firebaseui/dist/npm.js (npm.js:425)
    at __webpack_require__ (bootstrap:78)
    at Module../node_modules/firebaseui-angular/fesm2015/firebaseui-angular.js (firebaseui-angular.js:1)
```

![image](https://user-images.githubusercontent.com/5672108/58574684-31214c00-8249-11e9-9022-f50c71c4ce47.png)

Not sure where the issue is (haven't yet tried to reproduce on a clean project).
It might have to do with the Differential Loading introduced in Angular 8 (of the dialog polyfill).
https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27

**Update:** Disabling differential loading (by setting `"target": "es5"` in `tsconfig.json`), resolves the error.

**Comment by RaphaelJenni** [comment]
@anisabboud Thanks for the report. I'll check it out

**Comment by RaphaelJenni** [comment]
@anisabboud So I tested it out with a clean new angular 8 project.
Everything seems to work as expected. The target is set to `es2015`.
Can you create a sample project to reproduce this issue?

**Comment by RaphaelJenni** [comment]
I created a beta version where the plugin is built with the angular 8 cli. PLease give it a try:
`npm install firebaseui-angular@4.0.0-beta.0`

**Comment by PandiyanCool** [comment]
@RaphaelJenni doesn't work

**Comment by anisabboud** [comment]
Thank you @RaphaelJenni, but unfortunately the new beta didn't resolve the issue.

Seems like @LennyZ71 reported the same error here: https://github.com/firebase/firebaseui-web/issues/501#issuecomment-499984586.

I am able to reproduce with a fresh project created with Angular CLI 8.0.2:
- `ng new ng8project`
- `npm install firebase firebaseui @angular/fire firebaseui-angular@4.0.0-beta.0 --save`
- `app.module.ts` contents from the README https://github.com/RaphaelJenni/FirebaseUI-Angular
- `ng build` (not `serve`)
- `live-server dist/ng8project/ --entry-file=index.html`, then open http://localhost:8080/
- `Uncaught TypeError: Cannot read property 'Promise' of undefined` error in the console

If you switch `target` to `"es5"` in `tsconfig.json` (turns off differential loading), and run `ng build` again, the page loads fine.

**Comment by moblizeit** [comment]
for me locally all works fine just on deploying to firebase hosting gives this error.

{
  "name": "admin",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/fire": "^5.2.1",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "angular-gridster2": "^8.0.0",
    "angularfire2": "^5.0.0-rc.10",
    "chart.js": "^2.8.0",
    "firebase": "^5.11.1",
    "firebaseui": "^4.0.0",
    "firebaseui-angular": "^3.4.2",
    "ng2-charts": "^2.3.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.1",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

**Comment by PandiyanCool** [comment]
> for me locally all works fine just on deploying to firebase hosting gives this error.
> 
>Same for me as well

**Comment by LennyZ71** [comment]
I’m no expert but I think the issue lies in firebaseui itself.  With all the 8 upgrades angular has quite a few build issues.

‘’’  Object../node_modules/firebaseui/dist/npm.js (npm.js:425) ‘’’

**Comment by cstsortan** [comment]
I get the same behavior as @moblizeit. Any news on this?

**Comment by RaphaelJenni** [comment]
As someone pointed out, this is an issue with the firebaseui library and angular 8. I've already built the library with angular 8, but there isn't more at the moment that I can do. So I wait on any updates on the firebaseui side of things.

**Comment by Wullie-H62** [comment]
PandiyanCool thank you so much. I have been on the verge of giving up trying to build with Angular having  now spent several months through Angular 6, 7 then 8 without being able to complete a project.
I have struggled for several days now with my app working locally but not on deployment. 
Your work around switching the target to ES5 from ES2015 worked for me. Onwards and upwards.

**Comment by BeSpunky** [comment]
> for me locally all works fine just on deploying to firebase hosting gives this error.

Confirmed.
I can even do `ng serve --prod` and it works perfectly.
When I deploy to firebase or serve firebase locally (`firebase serve`) I get the error.

**Comment by wti806** [comment]
FirebaseUI added a es module in [v4.1.0](https://github.com/firebase/firebaseui-web/releases/tag/v4.1.0). Please upgrade to that version, it should solve the issue.

**Comment by anisabboud** [comment]
Thanks for the update, @wti806.

I updated FirebaseUI and switched back to `"target": "es2015"` in tsconfig.json.
- `ng build` worked successfully (both builds es2015 and es5 succeed) and running the app in the browser works without console errors.
- However, `ng build --prod` failed to complete the second build (tried multiple times):

```
 10% building 2/2 modules 0 active
<--- Last few GCs --->

[177:0x33e4710]   118958 ms: Mark-sweep 1917.1 (2074.4) -> 1908.2 (2076.4) MB, 564.7 / 0.0 ms  (average mu = 0.148, current mu = 0.101) allocation failure scavenge might not succeed
[177:0x33e4710]   119640 ms: Mark-sweep 1920.5 (2076.4) -> 1911.4 (2076.9) MB, 628.5 / 0.0 ms  (average mu = 0.113, current mu = 0.080) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1a8a982]
Security context: 0x2dedfee1a2f1 <JSObject>
    1: visitLiteralArrayExpr [0x2338ef395e99] [/mnt/c/Users/Anis/dev/myapp/node_modules/@angular/compiler/bundles/compiler.umd.js:~1986] [pc=0x2e7e9ac078b3](this=0x0a7b0a43b539 <_ApplySourceSpanTransformer map = 0x10dd68412339>,0x0a7b0a41bdf9 <LiteralArrayExpr map = 0x3bb3d3f9fbc9>,0x005389f801d9 <null>)
    2: visitExpression [0x2338ef3941e1] [/mnt/c...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x98db70 node::Abort() [ng build --prod]
 2: 0x98ebd6 node::OnFatalError(char const*, char const*) [ng build --prod]
 3: 0xb0b37e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --prod]
 4: 0xb0b6f9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --prod]
 5: 0xf15e75  [ng build --prod]
 6: 0xf207db v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng build --prod]
 7: 0xf214f7 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng build --prod]
 8: 0xf23f95 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [ng build --prod]
 9: 0xeeecac v8::internal::Factory::AllocateRawArray(int, v8::internal::PretenureFlag) [ng build --prod]
10: 0xeef47c v8::internal::Handle<v8::internal::FixedArray> v8::internal::Factory::NewFixedArrayWithMap<v8::internal::FixedArray>(v8::internal::RootIndex, int, v8::internal::PretenureFlag) [ng build --prod]    
11: 0x1056779 v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [ng build --prod]
12: 0x10567d9 v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [ng 
build --prod]
13: 0x109b0e5 v8::internal::JSObject::MigrateToMap(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Map>, int) [ng build --prod]
14: 0x102532e v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>) [ng build --prod]
15: 0x104d93c v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin) [ng build --prod]
16: 0x104e637 v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [ng build --prod]     
17: 0x11db937 v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>) [ng build --prod]
18: 0x11dca6a v8::internal::Runtime_SetKeyedProperty(int, unsigned long*, v8::internal::Isolate*) [ng build --prod]
19: 0x1a8a982  [ng build --prod]
Aborted (core dumped)
```

**Comment by BeSpunky** [comment]
Hi @anisabboud,

v4.1.0 fixed the problem for me.

Not sure if this is related, but how did you update your firebaseui package?
Try `npm update firebaseui`. It seemed to have updated `firebase` as well.

**Comment by anisabboud** [comment]
Thanks, @BeSpunky.

My packages are up-to-date, but I still get the "JavaScript heap out of memory" crash with `ng build --prod`.
Found the solution here: https://github.com/angular/angular-cli/issues/5618#issuecomment-450151214 (running ng build with higher memory).

Marking this as resolved, thank you all!
